---
- name: Deploy Eureka Registry Service
  gather_facts: false
  hosts: deployservers
  vars:
    jar_path: ./demo-0.0.1-SNAPSHOT.jar
    deploy_path: /home/gx/app-deployment/eureka-registry-service/
  tasks:
    - name: Gather the packege facts
      package_facts:
        manager: auto
    
    - name: Install Java if not already installed
      apt:
        name: default-jdk
        update_cache: yes
      when: "'default-jdk' not in ansible_facts.packages"

    - name: Copy eureka jar to the deployment server
      copy:
        src: "{{ jar_path }}"
        dest: "{{ deploy_path }}"
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Execute eureka registry service
      shell: "java -jar {{ deploy_path }}demo-0.0.1-SNAPSHOT.jar &"
      async: 45
      poll: 5
